In [11]:
import numpy as np

In [12]:
a= np.arange(5)

In [13]:
#Integers
a

array([0, 1, 2, 3, 4])

In [14]:
b= np.random.rand(5)

In [15]:
#Floats
b

array([0.44155252, 0.8622776 , 0.50615936, 0.02513306, 0.53800178])

In [16]:
c = np.array([1+2j, 3+4j, 5+6j])

In [18]:
#complex numbers
c.imag

array([2., 4., 6.])

In [19]:
a = np.arange(9, dtype = np.float_).reshape(3,3) 

b = np.array([10,10,10]) 

In [20]:
print(np.add(a,b))

[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


In [21]:
print(np.subtract(a,b))

[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


In [23]:
print(np.multiply(a,b))

[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


In [24]:
print(np.dot(a,b))

[ 30. 120. 210.]


In [25]:
a

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [28]:
a[0]

array([0., 1., 2.])

In [31]:
a[0,2]

2.0

In [26]:
#All rows, first column
a[:,0]

array([0., 3., 6.])

In [27]:
#All columns, first row
a[0,:]

array([0., 1., 2.])

In [32]:
import urllib.request

In [34]:
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12565616", 
                           filename = "avg-monthly-precip.txt")

('avg-monthly-precip.txt', <http.client.HTTPMessage at 0x1cc88c61cc8>)

In [36]:
avg_monthly_precip = np.loadtxt(fname = "avg-monthly-precip.txt")

In [37]:
avg_monthly_precip

array([0.7 , 0.75, 1.85, 2.93, 3.05, 2.02, 1.93, 1.62, 1.84, 1.31, 1.39,
       0.84])

In [39]:
np.mean(avg_monthly_precip)

1.6858333333333333

In [40]:
np.max(avg_monthly_precip)

3.05